%% sensitivity_tornado.m
% Phase 2 prompt 11 follow-on: sensitivity tornado plot.
%
% Reads the cohort generated by run_patient_cohort.m and computes the
% partial rank correlation coefficient (PRCC) between each sampled
% physiology parameter and the steady-state HR at the modified dose.
% Renders the result as a tornado plot: the bar lengths show which
% inputs matter most for the output (HR response).
%
% PRCC is the standard global sensitivity metric for Monte Carlo
% population pharmacology: it ranks samples first, then correlates,
% so it is robust to nonlinearities.
%
% Usage:
%   run('analysis/run_patient_cohort.m')   % populate cohortResults
%   run('analysis/sensitivity_tornado.m')

if ~evalin('base', 'exist(''cohortResults'', ''var'')')
    error('Run analysis/run_patient_cohort.m first to populate cohortResults.');
end

cohortResults = evalin('base', 'cohortResults');
patients      = evalin('base', 'patients');
nPatients     = numel(patients);

% Focus on the modified-dose half of the cohort.
modified_dose = 60;
mask    = arrayfun(@(r) r.dose == modified_dose, cohortResults);
hr_resp = [cohortResults(mask).hr_ss];

% Sanity check: there should be exactly nPatients samples at this dose.
assert(numel(hr_resp) == nPatients, 'Cohort layout mismatch.');

% Stack the per-patient sampled parameters in the same order.
X = [ ...
    [patients.pk_tau]', ...
    [patients.emax]', ...
    [patients.ec50]', ...
    [patients.hill_n]', ...
    [patients.baseline_hr]', ...
    [patients.sv]', ...
    [patients.svr]' ...
];

labels = { ...
    'PK time constant', ...
    'Emax', ...
    'EC50', ...
    'Hill n', ...
    'Baseline HR', ...
    'Stroke volume', ...
    'SVR' ...
};

%% ── PRCC ──────────────────────────────────────────────────────────────
% PRCC = correlation between ranked residuals of each input and the
% ranked residuals of the output, after regressing out the other inputs.
prcc = zeros(size(X, 2), 1);
for j = 1:size(X, 2)
    others = setdiff(1:size(X, 2), j);
    % Rank-transform inputs and output.
    rj  = tiedrank(X(:, j));
    ry  = tiedrank(hr_resp(:));
    rO  = tiedrank(X(:, others));
    % Regress out the other inputs and take residuals.
    rO  = [ones(nPatients, 1), rO];
    rj_resid = rj - rO * (rO \ rj);
    ry_resid = ry - rO * (rO \ ry);
    % Pearson correlation of the residuals = PRCC.
    prcc(j) = corr(rj_resid, ry_resid);
end

%% ── Tornado plot ──────────────────────────────────────────────────────
[~, order] = sort(abs(prcc), 'ascend');   % ascending so largest is on top
prcc_sorted   = prcc(order);
labels_sorted = labels(order);

figure('Name', 'Cardiac Digital Twin v2 -- PRCC sensitivity tornado', ...
    'Color', 'w', 'Position', [120 120 880 480]);

bh = barh(prcc_sorted, 'FaceColor', 'flat', 'EdgeColor', 'none');
for i = 1:numel(prcc_sorted)
    if prcc_sorted(i) >= 0
        bh.CData(i, :) = [0.20 0.45 0.85];
    else
        bh.CData(i, :) = [0.85 0.32 0.20];
    end
end
yticks(1:numel(labels_sorted));
yticklabels(labels_sorted);
xlabel(sprintf('PRCC vs HR steady state at %g mg', modified_dose));
title(sprintf('Parameter sensitivity (cohort n = %d)', nPatients));
grid on;
xline(0, 'k-', 'LineWidth', 0.5);
set(gca, 'FontSize', 11);

% Annotate each bar with the numeric PRCC.
for i = 1:numel(prcc_sorted)
    txt = sprintf(' %+.2f', prcc_sorted(i));
    if prcc_sorted(i) >= 0
        text(prcc_sorted(i), i, txt, 'VerticalAlignment','middle', ...
            'HorizontalAlignment','left',  'FontSize', 10);
    else
        text(prcc_sorted(i), i, txt, 'VerticalAlignment','middle', ...
            'HorizontalAlignment','right', 'FontSize', 10);
    end
end

%% ── Text summary ─────────────────────────────────────────────────────
fprintf('\n=========================================================\n');
fprintf('  PRCC SENSITIVITY (HR steady state at %g mg, n = %d)\n', modified_dose, nPatients);
fprintf('=========================================================\n');
for i = numel(prcc_sorted):-1:1
    fprintf('  %-22s  %+0.3f\n', labels_sorted{i}, prcc_sorted(i));
end
fprintf('=========================================================\n');
fprintf('  Interpretation:\n');
fprintf('  - |PRCC| near 1 means the parameter strongly drives HR.\n');
fprintf('  - Positive sign means increasing the parameter raises HR;\n');
fprintf('    negative sign means it lowers HR.\n');
fprintf('  - Use this to prioritise model calibration on the\n');
fprintf('    parameters with the largest |PRCC|.\n');
fprintf('=========================================================\n\n');
